# Generated by Django 4.1 on 2022-08-28 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('living', '生活費口座'), ('special', '特別費口座'), ('saving', '貯金口座')], default='living', max_length=9)),
                ('closed_on_month', models.IntegerField(default=1)),
                ('closed_in_year', models.IntegerField(default=2022)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=10)),
                ('day_close', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(choices=[('salary', '給料'), ('bonus', 'ボーナス'), ('other', 'その他')], default='salary', max_length=15)),
                ('income_money', models.IntegerField(default=0)),
                ('income_date', models.DateField(default=datetime.date.today)),
                ('income_memo', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_category', models.CharField(choices=[('food', '食費'), ('rent', '家賃'), ('education', '本、学習、勉強'), ('amuse', '娯楽費'), ('utility', '水道光熱通信サブスク費'), ('gaget', 'ガジェット'), ('beauty', '衣服・美容室'), ('dailyitem', '日用品'), ('special', '特別費・旅行費')], default='food', max_length=15)),
                ('spend_money', models.IntegerField(default=0)),
                ('spend_date', models.DateField(default=datetime.date.today)),
                ('spend_memo', models.TextField(blank=True, max_length=200)),
                ('spend_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.card')),
            ],
        ),
    ]
