# Generated by Django 4.1 on 2022-08-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_category', models.CharField(choices=[('food', '食費'), ('rent', '家賃'), ('education', '本、学習、勉強'), ('amuse', '娯楽費'), ('utility', '水道光熱通信サブスク費'), ('gaget', 'ガジェット'), ('beauty', '衣服・美容室'), ('dailyitem', '日用品'), ('special', '特別費・旅行費')], default='food', max_length=20)),
                ('spend_money', models.IntegerField(default=0)),
                ('spend_date', models.DateField(auto_now_add=True)),
                ('spend_memo', models.TextField(max_length=200)),
                ('spend_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
