# Generated by Django 4.1 on 2022-09-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livingcost', models.IntegerField(blank=True, default=0, null=True)),
                ('specialcost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
