# Generated by Django 4.1 on 2022-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='spend_memo',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
