# Generated by Django 4.1 on 2022-08-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_alter_spend_spend_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='spend_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
