# Generated by Django 4.1 on 2022-08-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_alter_spend_spend_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spend',
            name='spend_update',
        ),
    ]
