# Generated by Django 4.1 on 2022-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_alter_spend_spend_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='spend_category',
            field=models.CharField(choices=[('food', '食費'), ('rent', '家賃'), ('education', '本、学習、勉強'), ('amuse', '娯楽費'), ('utility', '水道光熱通信サブスク費'), ('gaget', 'ガジェット'), ('beauty', '衣服・美容室'), ('dailyitem', '日用品'), ('special', '特別費・旅行費')], default='food', max_length=20),
        ),
    ]
