# Generated by Django 4.1 on 2022-08-22 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_alter_spend_spend_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=10)),
                ('day_close', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(choices=[('salary', '給料'), ('bonus', 'ボーナス'), ('other', 'その他')], default='salary', max_length=15)),
                ('income_money', models.IntegerField(default=0)),
                ('income_date', models.DateField(default=datetime.date.today)),
                ('income_memo', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='spend',
            name='spend_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.card'),
        ),
    ]
