# Generated by Django 4.1 on 2022-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0008_card_income_spend_spend_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('living', '生活費口座'), ('special', '特別費口座'), ('saving', '貯金口座')], default='living', max_length=9)),
                ('closed_on', models.IntegerField()),
            ],
        ),
    ]
