# Generated by Django 4.1 on 2022-08-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0010_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='closed_on',
            field=models.CharField(max_length=10),
        ),
    ]
